# Generated by Django 4.1.5 on 2023-01-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True, unique=True)),
                ('description', models.TextField(default="Sabab ko'rsatilmagan")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', to_field='phone')),
            ],
        ),
    ]
