# Generated by Django 4.1.5 on 2023-01-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_davomat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='description',
            field=models.TextField(blank=True, default="Sabab ko'rsatilmagan", null=True),
        ),
    ]
