# Generated by Django 4.1.5 on 2023-01-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_davomat_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='davomat',
            options={'verbose_name': 'Davomat ', 'verbose_name_plural': 'Davomat '},
        ),
        migrations.AlterField(
            model_name='davomat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davomat', to='students.student', to_field='phone'),
        ),
    ]
