# Generated by Django 4.1.5 on 2023-01-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Room name')),
                ('student_count', models.CharField(max_length=150, verbose_name='Student Count')),
            ],
            options={
                'verbose_name': 'Room ',
                'verbose_name_plural': 'Rooms ',
            },
        ),
    ]
