# Generated by Django 4.1.5 on 2023-01-28 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_alter_davomat_options_alter_davomat_student'),
        ('courses', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group name')),
                ('education', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10, null=True)),
                ('day', models.CharField(blank=True, choices=[('juft', 'Juft kunlar'), ('toq', 'Toq kunlar')], max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('waiting', 'Waiting')], max_length=10, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('finish', models.DateField(blank=True, null=True)),
                ('course', models.ManyToManyField(related_name='groups', to='courses.course')),
                ('room', models.ManyToManyField(related_name='groups', to='courses.room')),
                ('student', models.ManyToManyField(to='students.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' Group ',
                'verbose_name_plural': ' Groups ',
                'db_table': 'Groups',
            },
        ),
    ]
